[package]
name = "dbman"
version = "0.0.0"
edition = "2021"
default-run = "controller"
authors = ["hef"]

[[bin]]
doc = false
name = "controller"
path = "src/main.rs"

[[bin]]
doc = false
name = "crdgen"
path = "src/crdgen.rs"

[lib]
name = "controller"
path = "src/lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4.0"
anyhow = "1.0.75"
clap = { version = "4.4.5", features = ["derive", "env"] }
env_logger = "0.10.0"
futures = "0.3.28"
k8s-openapi = { version = "0.20.0", features = ["v1_27"] }
kube = { version = "0.86.0", default-features = false, features = ["runtime", "derive", "client", "rustls-tls"] }
log = "0.4.20"
postgres-protocol = "0.6.6"
schemars = "0.8.15"
serde = { version = "1.0.188", features = ["derive", "serde_derive"] }
serde_json = "1.0.107"
serde_yaml = "0.9.25"
thiserror = "1.0.48"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
tokio-postgres = "0.7.10"

[profile.for-distribution]
inherits = "release"
lto=true
codegen-units=1
