apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "dbman.fullname" . }}
rules:
- apiGroups: ["dbman.hef.sh"]
  resources: ["databases", databaseservers]
  verbs: ["get", "list", "patch", "watch"]
- apiGroups: [""]
  resources: ["secret"]
  verbs: ["get"]