apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "dbman.fullname" . }}
rules:
- apiGroups: ["dbman.hef.sh"]
  resources: ["database", databaseserver]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secret"]
  verbs: ["get"]