apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "dbman.fullname" . }}
rules:
- apiGroups: ["dbman.hef.sh"]
  resources:
    - databases
    - databases/status #patch only?
    - databaseservers
  verbs: ["get", "list", "patch", "watch"]
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
