name: Rust

on:
  push:
    branches:
      - '**'
      - '!renovate/**'
      - '!release-please*'
  pull_request:
    branches: 
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }} 
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.11.0
      with:
        cluster_name: kind
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: prepare test environment
      run: cargo test test_prepare -- --exact
    - name: Run tests
      run: cargo test --verbose
